from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Client(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(100), nullable=False)
    alien_registration_number = db.Column(db.String(100))
    uscis_online_account_number = db.Column(db.String(100))
    date_of_birth = db.Column(db.String(100), nullable=False)
    country_of_birth = db.Column(db.String(100), nullable=False)
    country_of_citizenship = db.Column(db.String(100), nullable=False)
    ssn = db.Column(db.String(100))
    gender = db.Column(db.String(10))
    marital_status = db.Column(db.String(20))
    spouse_full_name = db.Column(db.String(100))
    marriage_date = db.Column(db.String(100))
    number_of_children = db.Column(db.Integer)
    children_names_dobs = db.Column(db.Text)
    physical_address = db.Column(db.Text, nullable=False)
    mailing_address = db.Column(db.Text)
    telephone_number = db.Column(db.String(15))
    email_address = db.Column(db.String(100))
    residential_history = db.Column(db.Text)
    employment_status = db.Column(db.String(100))
    current_employer_name_address = db.Column(db.Text)
    job_title = db.Column(db.String(100))
    start_date_current_job = db.Column(db.String(100))
    employment_history = db.Column(db.Text)
    previous_us_visas = db.Column(db.Text)
    previous_us_entries = db.Column(db.Text)
    deportation_history = db.Column(db.Text)
    criminal_history = db.Column(db.Text)
    political_social_orgs = db.Column(db.Text)
    languages_spoken = db.Column(db.Text)
    emergency_contact = db.Column(db.Text)
    other_citizenship = db.Column(db.Text)
    travel_purpose = db.Column(db.Text)
    countries_to_visit = db.Column(db.Text)
    length_of_trip = db.Column(db.Text)
    intended_departure_date = db.Column(db.String(100))
    travel_document_type = db.Column(db.String(100))
    summary = db.Column(db.Text)
